project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/"
  execute-dir: project

website:
  title: "Deploying AI in R with {ellmer} and {shiny} - From Experimentation to Production"
  navbar:
    background: dark
    right:
      - icon: file-certificate
        href: license-web.qmd
      - icon: github
        href: https://github.com/thisisnic/llms-shiny-workshop
        text: GitHub

    left:
      - href: index.qmd
        text: Home
      - text: Slides
        menu:
        - text: "Welcome and introduction 👋"
          href: materials/1_intro.qmd
          target: "_blank"
        - text: "Building LLM-powered Shiny apps"
          href: materials/2_llm_shiny.qmd
          target: "_blank"
        - text: "Deployment"
          href: materials/3_deployment.qmd
          target: "_blank"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
engine: knitr
execute:
  freeze: auto