project:
  type: website
  render:
    - "*.qmd"
    - "!exercises/"
  execute-dir: project

website:
  title: "Deploying AI in R with {ellmer} and {shiny} - From Experimentation to Production"
  navbar:
    background: dark
    right:
    left:
      - href: index.qmd
        text: Home
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual
engine: knitr
execute:
  freeze: auto